### ISSUE TITLE
400D and 500D Spherical embeddings for NER

### ISSUE THREAD

**Issue by alanakbik** [yumeng5/Spherical-Text-Embedding#11]
Hello, thanks for your interesting paper. I used your released embeddings in our standard NER architecture to see if they are useful for an NER downstream task. You can see the [comparison against other approaches on CoNLL-03](https://github.com/flairNLP/flair/issues/1486). As the table shows, F1 score increases with more dimensions to the point of being comparable to vanilla GloVe. It would be interesting to see if this trend continues with dimensions higher than 300D and if at higher dimensionality it beats vanilla GloVe. 

Would you be interested in also releasing spherical embeddings trained over the same data / parameters with 400D and 500D? If so, I'll test and report the numbers back.

**Comment by yumeng5** [comment]
Hi,

Thanks for your interest in our paper and for conducting the comparison! May I ask where did you obtain the pre-trained 100-d GloVe vectors? The "glove.6B.zip" version provided on the [GloVe page](https://nlp.stanford.edu/projects/glove/) is trained on both Wikipedia and the Gigaword corpus, while our released vectors are only trained on the Wikipedia corpus, which might make the comparison unfair.

Regarding higher dimensional embeddings, I haven't planned to release pre-trained embeddings with higher than 300 dimensions since I didn't see many people using >300-d embedding in their models, but you can always run our code on the Wikipedia corpus for arbitrary dimensions---both the code and the Wikipedia corpus are available in this repository. However, if you encounter any issues running our code, please let me know.

Best,
Yu

**Comment by alanakbik** [comment]
Thanks for your quick response - For vanilla GloVe, I used the embeddings released [here](https://github.com/alex-tifrea/poincare_glove) by the authors of the Poincaré Glove embeddings. They trained all embeddings on a 1.4 billion token dump of Wikpedia, so the numbers should be roughly comparable.

**Comment by yumeng5** [comment]
Thanks for letting me know. As I said in my previous response, since >300-d embeddings are not very common in applications, I don't have the embeddings of our model with >300 dimensions. But you can always run the code on the processed Wikipedia corpus with arbitrary dimensions--Just let me know if you have any problems or issues running the code.

Best,
Yu
