### ISSUE TITLE
Experiment setting

### ISSUE THREAD

**Issue by hyungsseop** [yumeng5/Spherical-Text-Embedding#13]
Hi, 

I ran run.sh and get_avg_emb to get the 20newsgroups embedded file. 

but, After embeddings, clustering was run, but it does not perform as well as the paper says.

How can I get an embedded file with that performance?

**Comment by yumeng5** [comment]
Hi @hyungsseop ,

I was wondering if you followed the document clustering instruction [here](https://github.com/yumeng5/Spherical-Text-Embedding#document-clustering-evaluation)? Basically, we use the learned document embeddings (instead of averaged word embeddings, which were intended to be ablations) as the features for clustering. Could you try running clustering in that way and let me know if you are able to obtain the performance reported in the paper?

Thanks,
Yu

**Comment by hyungsseop** [comment]
Hi, i'm sorry It's just that I did the wrong.

I got the same result as the paper! 

I'm experimenting with clustering on 20newsgroups.

If possible, can you tell me how to get the results of the experiment with doc2vec and average word2vec?

Thank you!

**Comment by yumeng5** [comment]
Hi @hyungsseop ,

Thanks for letting me know. The doc2vec embeddings can be obtained as described [here](https://radimrehurek.com/gensim/models/doc2vec.html), and the word2vec average embedding can be obtained by averaging the trained [word2vec](https://radimrehurek.com/gensim/models/word2vec.html) embeddings.

Thanks,
Yu
