### ISSUE TITLE
OOV problem

### ISSUE THREAD

**Issue by lsvih** [yumeng5/Spherical-Text-Embedding#9]
Hi there,
Is any suggestion to solve OOV problem? Should I using random value for it?
I didn't find tag like '<unk>' in vocab list but there is a 'unk' word

**Comment by yumeng5** [comment]
Hi,

Thanks for the question. It depends on how important the out-of-the-vocabulary words are to your task. For example, if you are doing sentiment classification and you have the quotation mark (``"``) as an OOV token, then it is not a good idea to use random embedding for it, since the quotation mark sometimes indicates the opposite meaning of the quoted words. The better way is to train (or fine-tune) the embeddings on your local corpus where the OOV token appears. 

That being said, the pre-trained embeddings I provided in the README file should cover pretty much all the common words (all in lower-case). Specifically, the quotation mark (``"``) appears at Line 13 of the pre-trained embedding files, so it is actually not an OOV token if you are using the pre-trained embeddings. Also, the ``unk`` token in the pre-trained embedding file does **NOT** represent unknown token embeddings; instead, it is simply the embedding of the real occurrences of the token ``unk`` in the corpus. In the wikipedia dump corpus, we never replaced unknown words with ``unk`` (in fact, words appearing less than ``100`` times in the corpus are simply discarded).

Please let me know if you have any futher questions!

Best,
Yu

**Comment by lsvih** [comment]
Thank you very much for your detailed explanation 😃
